all:
	gcc -W aes.c sha256.c client.c -o client -lgmp
	gcc -W aes.c sha256.c client_test.c -o client_test -lgmp
clean:
	rm client
	rm client_test
measandwich:
	gcc -W aes.c sha256.c client.c -o client -lgmp
	gcc -W aes.c sha256.c client_test.c -o client_test -lgmp
